//! Prelude reexports for the RustUse geometry facade.

#[cfg(feature = "affine")]
pub use crate::affine::*;
#[cfg(feature = "angle")]
pub use crate::angle::*;
#[cfg(feature = "archimedean")]
pub use crate::archimedean::*;
#[cfg(feature = "bezier")]
pub use crate::bezier::*;
#[cfg(feature = "bounds")]
pub use crate::bounds::*;
#[cfg(feature = "catalan-solid")]
pub use crate::catalan_solid::*;
#[cfg(feature = "cell")]
pub use crate::cell::*;
#[cfg(feature = "circle")]
pub use crate::circle::*;
#[cfg(feature = "complex")]
pub use crate::complex::*;
#[cfg(feature = "configuration")]
pub use crate::configuration::*;
#[cfg(feature = "congruence")]
pub use crate::congruence::*;
#[cfg(feature = "conic")]
pub use crate::conic::*;
#[cfg(feature = "containment")]
pub use crate::containment::*;
#[cfg(feature = "coordinate")]
pub use crate::coordinate::*;
#[cfg(feature = "coxeter")]
pub use crate::coxeter::*;
#[cfg(feature = "crease")]
pub use crate::crease::*;
#[cfg(feature = "curve")]
pub use crate::curve::*;
#[cfg(feature = "delaunay")]
pub use crate::delaunay::*;
#[cfg(feature = "dihedral")]
pub use crate::dihedral::*;
#[cfg(feature = "dimension")]
pub use crate::dimension::*;
#[cfg(feature = "distance")]
pub use crate::distance::*;
#[cfg(feature = "duality")]
pub use crate::duality::*;
#[cfg(feature = "face")]
pub use crate::face::*;
#[cfg(feature = "folding")]
pub use crate::folding::*;
#[cfg(feature = "hull")]
pub use crate::hull::*;
#[cfg(feature = "hyperplane")]
pub use crate::hyperplane::*;
#[cfg(feature = "hypersphere")]
pub use crate::hypersphere::*;
#[cfg(feature = "incidence")]
pub use crate::incidence::*;
#[cfg(feature = "intersection")]
pub use crate::intersection::*;
#[cfg(feature = "inversion")]
pub use crate::inversion::*;
#[cfg(feature = "johnson-solid")]
pub use crate::johnson_solid::*;
#[cfg(feature = "line")]
pub use crate::line::*;
#[cfg(feature = "linkage")]
pub use crate::linkage::*;
#[cfg(feature = "manifold")]
pub use crate::manifold::*;
#[cfg(feature = "mesh")]
pub use crate::mesh::*;
#[cfg(feature = "orientation")]
pub use crate::orientation::*;
#[cfg(feature = "origami")]
pub use crate::origami::*;
#[cfg(feature = "orthotope")]
pub use crate::orthotope::*;
#[cfg(feature = "plane")]
pub use crate::plane::*;
#[cfg(feature = "point")]
pub use crate::point::*;
#[cfg(feature = "polygon")]
pub use crate::polygon::*;
#[cfg(feature = "polyhedral-net")]
pub use crate::polyhedral_net::*;
#[cfg(feature = "polyhedron")]
pub use crate::polyhedron::*;
#[cfg(feature = "polyline")]
pub use crate::polyline::*;
#[cfg(feature = "polytope")]
pub use crate::polytope::*;
#[cfg(feature = "projection")]
pub use crate::projection::*;
#[cfg(feature = "projective")]
pub use crate::projective::*;
#[cfg(feature = "ray")]
pub use crate::ray::*;
#[cfg(feature = "rectangle")]
pub use crate::rectangle::*;
#[cfg(feature = "reflection")]
pub use crate::reflection::*;
#[cfg(feature = "regular-polytope")]
pub use crate::regular_polytope::*;
#[cfg(feature = "rigid-folding")]
pub use crate::rigid_folding::*;
#[cfg(feature = "schlafli")]
pub use crate::schlafli::*;
#[cfg(feature = "segment")]
pub use crate::segment::*;
#[cfg(feature = "similarity")]
pub use crate::similarity::*;
#[cfg(feature = "simplex")]
pub use crate::simplex::*;
#[cfg(feature = "sphere")]
pub use crate::sphere::*;
#[cfg(feature = "spline")]
pub use crate::spline::*;
#[cfg(feature = "surface")]
pub use crate::surface::*;
#[cfg(feature = "tessellation")]
pub use crate::tessellation::*;
#[cfg(feature = "torus")]
pub use crate::torus::*;
#[cfg(feature = "transform")]
pub use crate::transform::*;
#[cfg(feature = "triangle")]
pub use crate::triangle::*;
#[cfg(feature = "triangulation")]
pub use crate::triangulation::*;
#[cfg(feature = "unfolding")]
pub use crate::unfolding::*;
#[cfg(feature = "uniform-polytope")]
pub use crate::uniform_polytope::*;
#[cfg(feature = "voronoi")]
pub use crate::voronoi::*;
#[cfg(feature = "wythoff")]
pub use crate::wythoff::*;
